# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: out

jobs:
# Please do not rename this job
  build-project:
    name: build marketplace-front
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      - name: Build Node assets
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
          TOKEN_STORAGE_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweGYzYzJGNjEwYjVCRTlEMTdkMkVlQTI2MENlOTY4ZjNlNTc4Mzg1YUMiLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTY2NDQ3NTg0MDA2NiwibmFtZSI6Ik1hcmtldHBsYWNlIn0.bXmRQGpzYAz4gQD2lFrd19BzBL-nP6Hrb3YYOFbecu8
        run: |
          npm ci
          npm run build
          npm run export

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: f2f54b86-4d9b-462a-935c-df7fe4e4ebcb
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/marketplace-front/config.yaml
          action: upload
